### ISSUE TITLE
Issue with border color

### ISSUE THREAD

**Issue by RyanLiu1900** [widatama/hexo-jade-starter#5]
Unhandled rejection Error: variable @border-color is undefined

**Comment by saracen9** [comment]
Same here, running hexo: 3.1.1
Assume it's not being loaded correctly from [variables.less](https://github.com/widatama/hexo-jade-barebone/blob/master/source/stylesheets/_base/variables.less)

**Comment by widatama** [comment]
This should be fixed with the latest update for Hexo 3.
